apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samba-config-kube-pvc
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list