name: Go-branches

on:
  push:
    - '*'
    - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build Docker & Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cnieg/samba-config-kube-pvc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{GITHUB_REF##*/}}-${{ github.run_number }}






