name: Go-branches

on:
  push:
    - '*'
    - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      ‐ name: Build docker
        id: build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{GITHUB_REPOSITORY}}
          push: false
          tag_with_ref: true






