name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build docker
        id: build
        uses: docker/build-push-action@v1
        with:
          repository: ${{GITHUB_REPOSITORY}}
          push: true
          tag_with_ref: true

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: |
            Samba config kube pvc v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Push docker
        id: push_docker
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{GITHUB_REPOSITORY}}
          push: true
          tag_with_ref: true

      - name: Upload Linux Release Asset
        id: upload-linux-release-asset
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/samba-config-kube-pvc
          asset_name: samba-config-kube-pvc_linux_amd64
          asset_content_type: application/octet-stream

