name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build & Push docker image
        id: build_docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{github.repository}}
          push: true
          tag_with_ref: true
          add_git_labels: true
          build_args: BIN_OUTPUT_DIRECTORY=/github/workspace/bin

      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la && ls -altr bin/

      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: |
            Samba config kube pvc v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Push docker image release
        id: push_docker_release
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{github.repository}}
          push: true
          tags: v1.0.${{ github.run_number }}
          add_git_labels: true
          build_args: BIN_OUTPUT_DIRECTORY=/github/workspace/bin

      - name: Upload Linux Release Asset
        id: upload-linux-release-asset
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/samba-config-kube-pvc
          asset_name: samba-config-kube-pvc_linux_amd64
          asset_content_type: application/octet-stream

